name: CI

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install
      run: |
        yarn install --force
        yarn bootstrap

    - name: Configure CI Git User
      run: |
        git config --global user.email octobot@github.com
        git config --global user.name GitHub Actions

    - name: bump
      run: yarn bump --yes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: release
      run: yarn release
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}